#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""
collect.py — find every OPEN-ITEMS.md, merge the open items, write a rollup.

Usage:
    uv run collect.py               # read config, write rollup.md and rollup.json
    uv run collect.py --print       # also print the rollup to stdout
    uv run collect.py --config path/to/config.yaml

Config lives at ~/.open-items/config.yaml. See templates/config.yaml.

This is deterministic. No model is involved: walking directories, parsing, merging
and sorting are fully specified operations. The agent's job is the judgment ("is
this done?"); this script's job is the mechanics ("what exists?").
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

import yaml

from ledger import find_ledgers, parse_ledger

DEFAULT_CONFIG = Path.home() / ".open-items" / "config.yaml"

FALLBACK = {
    "scan_roots": ["<scan-root>"],
    "exclude": [],
    "output_dir": "~/.open-items",
    "extra_outputs": [],
}


def load_config(path: Path) -> dict:
    if not path.exists():
        print(f"no config at {path}, using defaults", file=sys.stderr)
        return dict(FALLBACK)
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    merged = dict(FALLBACK)
    merged.update(data)
    return merged


def build_rollup(config: dict) -> dict:
    roots = [Path(r).expanduser() for r in config.get("scan_roots", [])]
    excludes = list(config.get("exclude", []))

    ledger_paths = find_ledgers(roots, excludes)
    scopes: list[dict] = []
    problems: list[str] = []
    prefixes: dict[str, str] = {}

    for path in ledger_paths:
        led = parse_ledger(path)

        if led.errors:
            problems.append(f"{path}: {len(led.errors)} format error(s) — run check_ledger.py")

        prefix = led.prefix or "?"
        if prefix in prefixes and prefixes[prefix] != str(path):
            problems.append(
                f"prefix {prefix!r} used by both {prefixes[prefix]} and {path}"
            )
        prefixes.setdefault(prefix, str(path))

        scopes.append({
            "title": led.title,
            "prefix": prefix,
            "path": str(path),
            "folder": str(path.parent),
            "updated": led.updated,
            "items": [
                {
                    "id": item.ident,
                    "text": item.text,
                    "opened": item.opened,
                    "path": item.path,
                }
                for item in sorted(
                    led.open_items(),
                    key=lambda i: (i.opened or "9999-99-99", i.number),
                )
            ],
        })

    scopes.sort(key=lambda s: s["title"].lower())

    return {
        "generated": date.today().isoformat(),
        "ledger_count": len(scopes),
        "open_count": sum(len(s["items"]) for s in scopes),
        "problems": problems,
        "scopes": scopes,
    }


def render_markdown(rollup: dict) -> str:
    lines = [
        "---",
        "title: Open Items — Rollup",
        "type: rollup",
        f"generated: {rollup['generated']}",
        "note: Generated by collect.py. Do not edit — edits are overwritten.",
        "---",
        "",
        "# Open Items — Rollup",
        "",
        f"{rollup['open_count']} open across {rollup['ledger_count']} ledgers. "
        f"Generated {rollup['generated']}.",
        "",
    ]

    if rollup["problems"]:
        lines.append("## Problems")
        lines.append("")
        for problem in rollup["problems"]:
            lines.append(f"- {problem}")
        lines.append("")

    for scope in rollup["scopes"]:
        stale = ""
        if scope["updated"] and scope["updated"] < rollup["generated"]:
            stale = f" · last updated {scope['updated']}"
        lines.append(f"## {scope['title']} [{scope['prefix']}]{stale}")
        lines.append("")
        lines.append(f"`{scope['folder']}`")
        lines.append("")
        if not scope["items"]:
            lines.append("Nothing open.")
        else:
            for item in scope["items"]:
                suffix = f" · {item['path']}" if item["path"] else ""
                lines.append(
                    f"- [ ] **{item['id']}** — {item['text']} "
                    f"· opened {item['opened']}{suffix}"
                )
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Roll up open items across ledgers.")
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--print", action="store_true", dest="do_print")
    args = parser.parse_args()

    config = load_config(args.config)
    rollup = build_rollup(config)
    markdown = render_markdown(rollup)

    out_dir = Path(config["output_dir"]).expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "rollup.md").write_text(markdown, encoding="utf-8")
    (out_dir / "rollup.json").write_text(
        json.dumps(rollup, indent=2) + "\n", encoding="utf-8"
    )

    for extra in config.get("extra_outputs", []):
        target = Path(extra).expanduser()
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(markdown, encoding="utf-8")

    if args.do_print:
        print(markdown)
    else:
        print(
            f"{rollup['open_count']} open across {rollup['ledger_count']} ledgers "
            f"-> {out_dir / 'rollup.md'}"
        )

    for problem in rollup["problems"]:
        print(f"  ! {problem}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
